### ISSUE TITLE
Models not persisted in the DB

### ISSUE THREAD

**Issue by frowing** [lonelyplanet/lpm-sirenkit-ios#5]
Hi @groomsy! I wonder if there is any particular reason why the models weren't being persisted in the DB after being retrieved? Was it intentional? I had to add `[CDMDataManager.sharedManager persist:YES];` all over in the Session Manager.

**Comment by groomsy** [comment]
@frowing It was probably accidental :pensive:.

**Comment by frowing** [comment]
Fixed in https://github.com/lonelyplanet/lpm-sirenkit-ios/pull/4
